# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Create a new application on App Store Connect and push a new beta build to TestFlight"
  lane :beta do
    # Create a new application on App Store Connect
    produce(
      username: "jhlee909090@naver.com",
      app_identifier: "com.JMT-iOSJMTengg", 
      app_name: "JMTeng - 우리만의 맛집리스트",
      language: "Korean",
      app_version: "1.0.1",
      sku: "com.JMT-iOSJMTengg"
    )
    
    # Increment the build number
    increment_build_number(workspace: "JMT-iOS.xcworkspace")


    # Build the app
    build_app(workspace: "JMT-iOS.xcworkspace", scheme: "Jmteng")

    # Upload the app to TestFlight
    upload_to_testflight
  end
end
